apiVersion: v1
kind: Secret
metadata:
  name: git-root-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/mikamboo/platform-starter-kit.git