apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - chart: crossplane
      repoURL: https://charts.crossplane.io/stable
      targetRevision: 2.0.2
      helm:
        releaseName: crossplane
        valueFiles:
          - $values/helm/crossplane/values.yaml
    - repoURL: https://github.com/mikamboo/platform-starter-kit.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
