---
# Sample pod manifest
apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  namespace: default
spec:
  containers:
    - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
      imagePullPolicy: Always
      name: app-2048
      ports:
      - containerPort: 80