# Argo App of Apps Pattern Root Application
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # Prevents accidental deletion
  annotations:
    argocd.argoproj.io/sync-wave: "-1"        # Deploy root app first
spec:
  project: default
  source:
    repoURL: {{ .Values.base.repoURL }}
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  info:
    - name: 'Description'
      value: 'Platform starter kit root application managing all child apps'
  revisionHistoryLimit: 20